name: Build CI environments

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Ubuntu CI images
    uses: ./.github/workflows/build-ci-images.yml
    with:
      image: ${{ github.repository_owner }}/alamo-ci
    secrets:
      registry_token: ${{ secrets.GITHUB_TOKEN }}

  macos:
    name: macOS native environment
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-macos
